In [2]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import to_categorical
from keras.preprocessing import image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical

# Montar Google Drive
from google.colab import drive
drive.mount('/content/drive')

(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

x_train.shape,x_test.shape

Mounted at /content/drive
170498071/170498071 [==============================] - 2s 0us/step


((50000, 32, 32, 3), (10000, 32, 32, 3))

In [3]:
# Normalización
x_train = x_train/255.0
x_test = x_test/255.0

# Promediar las tres bandas RGB para obtener una imagen es tonos de gris
x_train = np.mean(x_train, axis=3)
x_test = np.mean(x_test, axis=3)
x_train.shape,x_test.shape

((50000, 32, 32), (10000, 32, 32))

In [5]:
# Definir la estructura del modelo
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=(32,32,1)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

# Compilar el modelo
model.compile(loss='sparse_categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [6]:
# Entrenar el modelo
model.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test))

Epoch 1/10
1563/1563 [==============================] - 201s 128ms/step - loss: 1.7540 - accuracy: 0.3652 - val_loss: 1.3796 - val_accuracy: 0.5173
Epoch 2/10
1563/1563 [==============================] - 204s 130ms/step - loss: 1.4321 - accuracy: 0.4891 - val_loss: 1.2319 - val_accuracy: 0.5707
Epoch 3/10
1563/1563 [==============================] - 213s 136ms/step - loss: 1.3133 - accuracy: 0.5340 - val_loss: 1.1326 - val_accuracy: 0.6057
Epoch 4/10
1563/1563 [==============================] - 193s 123ms/step - loss: 1.2373 - accuracy: 0.5630 - val_loss: 1.1011 - val_accuracy: 0.6180
Epoch 5/10
1563/1563 [==============================] - 191s 123ms/step - loss: 1.1725 - accuracy: 0.5900 - val_loss: 1.0570 - val_accuracy: 0.6390
Epoch 6/10
1563/1563 [==============================] - 190s 122ms/step - loss: 1.1206 - accuracy: 0.6076 - val_loss: 1.0355 - val_accuracy: 0.6402
Epoch 7/10
1563/1563 [==============================] - 188s 120ms/step - loss: 1.0808 - accuracy: 0.6182 - val_

In [7]:
# Hacer predicciones
df = pd.read_csv("/content/drive/MyDrive/Taller_IA/datos_2.csv")
test = df.values[:,1]
test = test.reshape((1,32,32))/255.0
print(test)
prediction = model.predict(test)
print(prediction)
print(prediction.argmax(axis=1))


[[[0.5372549  0.54509804 0.54509804 ... 0.60392157 0.60392157 0.60392157]
  [0.5372549  0.54117647 0.54509804 ... 0.6        0.6        0.60392157]
  [0.5372549  0.54117647 0.54901961 ... 0.6        0.60392157 0.60392157]
  ...
  [0.53333333 0.54117647 0.54509804 ... 0.58431373 0.58823529 0.58823529]
  [0.53333333 0.5372549  0.54509804 ... 0.58431373 0.58431373 0.58431373]
  [0.53333333 0.5372549  0.54117647 ... 0.58431373 0.58431373 0.58431373]]]
1/1 [==============================] - 0s 195ms/step
[[0.22876774 0.00820826 0.19814475 0.10966023 0.13706283 0.02308405
  0.02426015 0.00757392 0.25406325 0.00917487]]
[8]
